schema:
  - "http://localhost:4000/"
documents:
  - "src/components/particles/graphql/**/*.graphql"
generates:
  src/components/particles/graphql/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
